#!/usr/bin/env sh

set -e

echo "Running pre-commit checks..."

echo "Generating i18n files..."
pnpm gen:i18n

echo "Running lint-staged..."
pnpm lint-staged

echo "Running build and storybook:build..."
pnpm build
pnpm storybook:build

echo "Running all the tests to check the coverage..."
pnpm test

echo "Pre-commit checks passed!"
