#!/usr/bin/env sh

set -e

echo "Running pre-commit checks..."

echo "Generating i18n files..."
yarn gen:i18n

echo "Running lint-staged..."
yarn lint-staged

echo "Running build and storybook:build..."
yarn build
yarn storybook:build

echo "Running all the tests to check the coverage..."
yarn test

echo "Pre-commit checks passed!"
