name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.9
        with:
          version: 9.15.4

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: |
          cp .env.dist .env # to avoid vite env verified plugin to fail
          pnpm test

      - name: Storybook build
        run: pnpm storybook:build

      - name: Build
        # Vite will also need that .env file here to pass validation
        run: pnpm build
